## Numpy

Импортировать NumPy под именем np
https://pythonworld.ru/numpy/100-exercises.html

In [17]:
import numpy as np
print(np.__version__)
np.show_config()

1.14.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/nazhmeddinbabakhanov/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/nazhmeddinbabakhanov/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/nazhmeddinbabakhanov/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/nazhmeddinbabakhanov/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/nazhmeddinbabakhanov/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/nazhmeddinbabakhanov/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/nazhmeddinbabakhanov/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/nazhmeddinbabakhanov/anac

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
a = np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [6]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [18]:
a = np.array([2.5 for i in range(10)])
Z = np.full(10, 2.5)
print(Z)


[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [20]:
!python3 -c "import numpy; numpy.info(numpy.full)"

 full(shape, fill_value, dtype=None, order='C')

Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, `None`, means
     `np.array(fill_value).dtype`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of `fill_value` with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
ones_like : Return an array of ones with shape and type of input.
empty_like : Return an empty array with shape and type of input.
full_like : Fill an array with shape and type of input.
zeros : Return a new array setting values to zero.
ones : Return a new array setting value

In [24]:
a = np.zeros(10)
a[5]=1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [25]:
a = a[::-1]
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [28]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [31]:
z = np.nonzero([1,2,0,0,4,0])
z

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [36]:
t = np.full([3,3],1)
t1 = np.eye(3)
t1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [39]:
t3 = np.random.random((3,3,3))
t3

array([[[0.59672134, 0.01436393, 0.52560018],
        [0.77659413, 0.34712805, 0.75359   ],
        [0.91856325, 0.84414973, 0.69914924]],

       [[0.08162962, 0.84049163, 0.2335228 ],
        [0.07444849, 0.90875748, 0.28664401],
        [0.16025256, 0.71252317, 0.81150916]],

       [[0.33732244, 0.04320661, 0.12983405],
        [0.27617188, 0.2021121 , 0.52915388],
        [0.1319632 , 0.11467234, 0.02253179]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [44]:
t4 = np.random.random(30)
print(t4.sum(), t4.mean())

15.920138539690418 0.5306712846563473


Перемножить матрицы 5x3 и 3x2

In [50]:
t5 = np.random.random((5,3))  
t6 = np.random.random((3,2))
np.dot(t5,t6)

array([[0.18528808, 0.34692547],
       [0.56627491, 0.44807433],
       [0.17100106, 0.26979629],
       [0.70806398, 0.74735173],
       [0.65320705, 0.8028885 ]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [54]:
t5=np.linspace(0,1,12)

Заменить максимальный элемент на ноль

In [57]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.63693307 0.34973215 0.19326575 0.14969117 0.91567725 0.15021087
 0.55127954 0.23225184 0.00481443 0.72209768]
[0.63693307 0.34973215 0.19326575 0.14969117 0.         0.15021087
 0.55127954 0.23225184 0.00481443 0.72209768]


Преобразовать массив из float в int

In [60]:
Z = np.arange(10,dtype=float)
Z = Z.astype(np.int,copy=False)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [61]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.40148549 0.44611483 0.30675469 0.79825662 0.13311899
  0.09529901 0.42493425 0.27050994 0.17221448]
 [0.40148549 0.         0.17267678 0.27319692 0.50112469 0.45746981
  0.47178207 0.02344889 0.31359547 0.5051823 ]
 [0.44611483 0.17267678 0.         0.18995047 0.36343299 0.45150399
  0.53449848 0.17299256 0.45332496 0.49202008]
 [0.30675469 0.27319692 0.18995047 0.         0.50132853 0.27496636
  0.40187179 0.28895834 0.42309103 0.31024752]
 [0.79825662 0.50112469 0.36343299 0.50132853 0.         0.77486141
  0.89045038 0.4884733  0.80916723 0.80588545]
 [0.13311899 0.45746981 0.45150399 0.27496636 0.77486141 0.
  0.1990779  0.48005298 0.39691989 0.04905907]
 [0.09529901 0.47178207 0.53449848 0.40187179 0.89045038 0.1990779
  0.         0.49497556 0.2738369  0.22249206]
 [0.42493425 0.02344889 0.17299256 0.28895834 0.4884733  0.48005298
  0.49497556 0.         0.3312747  0.52760845]
 [0.27050994 0.31359547 0.45332496 0.42309103 0.80916723 0.39691989
  0.2738369  0.331274

Случайно расположить p элементов в 2D массив

In [62]:
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [63]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [66]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[9 6 9 1 0 5 0 6 7 4 3 0 3 3 5 2 8 5 7 5 4 7 8 5 4 6 8 6 5 0 8 9 0 7 7 7 9
 9 4 4 7 0 6 6 8 9 1 4 2 4]
4


Найти n наибольших значений в массиве

In [67]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9999 9997 9998 9996 9995]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [79]:
import pandas as pd
df=pd.read_csv("en.openfoodfacts.org.products.tsv", delimiter="\t")

/Users/nazhmeddinbabakhanov/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [76]:
df.head(5)

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

In [77]:
df.describe()

no_nutriments    additives_n  ingredients_from_palm_oil_n  \
count            0.0  283867.000000                283867.000000   
mean             NaN       1.876851                     0.023430   
std              NaN       2.501022                     0.153094   
min              NaN       0.000000                     0.000000   
25%              NaN       0.000000                     0.000000   
50%              NaN       1.000000                     0.000000   
75%              NaN       3.000000                     0.000000   
max              NaN      30.000000                     2.000000   

       ingredients_from_palm_oil  ingredients_that_may_be_from_palm_oil_n  \
count                        0.0                            283867.000000   
mean                         NaN                                 0.059736   
std                          NaN                                 0.280660   
min                          NaN                                 0.000000   
25%                          NaN                                 0.000000   
50%                          NaN                                 0.000000   
75%                          NaN                                 0.000000   
max                          NaN                                 6.000000   

       ingredients_that_may_be_from_palm_oil  nutrition_grade_uk  \
count                                    0.0                 0.0   
mean                                     NaN                 NaN   
std                                      NaN                 NaN   
min                                      NaN                 NaN   
25%                                      NaN                 NaN   
50%                                      NaN                 NaN   
75%                                      NaN                 NaN   
max                                      NaN                 NaN   

         energy_100g  energy-from-fat_100g      fat_100g         ...           \
count  295367.000000            869.000000  2.794970e+05         ...            
mean     1125.453320            587.216617  5.606587e+04         ...            
std       936.825952            713.255708  2.963385e+07         ...            
min         0.000000              0.000000  0.000000e+00         ...            
25%       382.000000             49.400000  1.000000e-01         ...            
50%      1092.000000            300.000000  5.290000e+00         ...            
75%      1674.000000            900.000000  2.000000e+01         ...            
max    231199.000000           3830.000000  1.566667e+10         ...            

       fruits-vegetables-nuts_100g  fruits-vegetables-nuts-estimate_100g  \
count                  3228.000000                            404.000000   
mean                     33.392680                             60.360124   
std                      32.906834                             29.262350   
min                       0.000000                              0.000000   
25%                       0.000000                             45.000000   
50%                      25.000000                             58.000000   
75%                      55.000000                             93.000000   
max                     100.000000                            100.000000   

       collagen-meat-protein-ratio_100g   cocoa_100g  chlorophyl_100g  \
count                        182.000000  1383.000000              0.0   
mean                          15.362637    52.102675              NaN   
std                            3.692658    19.028361              NaN   
min                            8.000000     6.000000              NaN   
25%                           12.000000    33.000000              NaN   
50%                           15.000000    52.000000              NaN   
75%                           15.000000    70.000000              NaN   
max                           25.000000   100.000000              NaN   

       carbon-

Сколько наблюдений в наборе данных?


In [81]:
df.shape

(356027, 163)

Сколько столбцов в наборе данных?

Напечатайте все названия столбцов

In [82]:
df.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [84]:
df.columns[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [85]:
type(df.columns[105])

str

Как проиндексирован набор данных?

In [86]:
df.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [101]:
df[19:20]

code                                                url          creator  \
19  18227  http://world-en.openfoodfacts.org/product/0000...  usda-ndb-import   

     created_t      created_datetime last_modified_t last_modified_datetime  \
19  1489055682  2017-03-09T10:34:42Z      1489055682   2017-03-09T10:34:42Z   

          product_name generic_name quantity         ...          \
19  Organic Oat Groats          NaN      NaN         ...           

   fruits-vegetables-nuts_100g fruits-vegetables-nuts-estimate_100g  \
19                         NaN                                  NaN   

   collagen-meat-protein-ratio_100g cocoa_100g chlorophyl_100g  \
19                              NaN        NaN             NaN   

   carbon-footprint_100g nutrition-score-fr_100g nutrition-score-uk_100g  \
19                   NaN                    -6.0                    -6.0   

   glycemic-index_100g water-hardness_100g  
19                 NaN                 NaN  

[1 rows x 163 columns]

In [90]:
a = "AB"
b = "BC"
print("%sa, b" % a, b)

ABa, b BC


## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [111]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", delimiter="\t")

In [ ]:
# df.item_price = pd.to_numeric(df.item_price.str[1:])

Как много продуктов стоят более чем $10.00?

In [169]:
df[pd.to_numeric(df.item_price.str[1:])>10]

order_id  quantity           item_name  \
4            2         2        Chicken Bowl   
5            3         1        Chicken Bowl   
7            4         1       Steak Burrito   
13           7         1        Chicken Bowl   
23          12         1     Chicken Burrito   
39          19         1       Barbacoa Bowl   
42          20         1        Chicken Bowl   
43          20         1       Steak Burrito   
45          21         1     Chicken Burrito   
52          24         1     Chicken Burrito   
57          26         1      Veggie Burrito   
58          27         1       Barbacoa Bowl   
62          28         1         Veggie Bowl   
68          30         1     Chicken Burrito   
79          35         1  Chicken Soft Tacos   
90          40         1          Steak Bowl   
91          40         1          Steak Bowl   
93          41         1    Carnitas Burrito   
97          43         1       Carnitas Bowl   
123         54         1        Chicken Bowl   
130         57         1    Barbacoa Burrito   
134         59         1     Chicken Burrito   
135         60         2  Chicken Salad Bowl   
136         61         1       Barbacoa Bowl   
138         62         1        Chicken Bowl   
140         63         1        Chicken Bowl   
142         64         1        Chicken Bowl   
143         64         1         Veggie Bowl   
144         65         1    Barbacoa Burrito   
147         66         1       Steak Burrito   
...        ...       ...                 ...   
4504      1791         1       Carnitas Bowl   
4506      1792         1        Chicken Bowl   
4510      1793         1       Barbacoa Bowl   
4518      1796         1          Steak Bowl   
4521      1798         1     Chicken Burrito   
4523      1798         1  Steak Crispy Tacos   
4533      1802         1     Chicken Burrito   
4540      1805         1        Chicken Bowl   
4553      1810         1        Chicken Bowl   
4554      1810         1  Steak Crispy Tacos   
4556      1811         1     Chicken Burrito   
4559      1812         1     Chicken Burrito   
4561      1813         2  Chicken Salad Bowl   
4564      1815         1        Chicken Bowl   
4576      1820         1        Chicken Bowl   
4580      1822         1  Chicken Salad Bowl   
4586      1824         1        Chicken Bowl   
4587      1824         1        Chicken Bowl   
4589      1825         1        Chicken Bowl   
4590      1825         1        Chicken Bowl   
4592      1825         1    Barbacoa Burrito   
4593      1825         1       Carnitas Bowl   
4594      1825         1       Barbacoa Bowl   
4607      1829         1       Steak Burrito   
4608      1829         1      Veggie Burrito   
4610      1830         1       Steak Burrito   
4611      1830         1      Veggie Burrito   
4617      1833         1       Steak Burrito   
4618      1833         1       Steak Burrito   
4619      1834         1  Chicken Salad Bowl   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
7     [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
23    [[Tomatillo-Green Chili Salsa (Medium), Tomati...    $10.98   
39    [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $11.75   
42    [Roasted Chili Corn Salsa, [Rice, Black Beans,...    $11.25   
43    [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...    $11.75   
45    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $10.98   
52    [Roasted Chili Corn Salsa (Medium), [Black Bea...    $10.98   
57    [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.25   
58    [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $11.75   
62    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
68    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $10.

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [150]:
df[["item_name", "item_price"]]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17                          Chicken Burrito     $8.49 
18                              Canned Soda     $2.18 
19                             Chicken Bowl     $8.75 
20                      Chips and Guacamole     $4.45 
21                         Barbacoa Burrito     $8.99 
22                         Nantucket Nectar     $3.39 
23                          Chicken Burrito    $10.98 
24                                     Izze     $3.39 
25             Chips and Fresh Tomato Salsa     $2.39 
26                             Chicken Bowl     $8.49 
27                         Carnitas Burrito     $8.99 
28                              Canned Soda     $1.09 
29                          Chicken Burrito     $8.49 
...                                     ...        ...
4592                       Barbacoa Burrito    $11.75 
4593                          Carnitas Bowl    $11.75 
4594                          Barbacoa Bowl    $11.75 
4595                           Chicken Bowl     $8.75 
4596                    Chips and Guacamole     $4.45 
4597                      Canned Soft Drink     $1.25 
4598                          Bottled Water     $1.50 
4599                           Chicken Bowl     $8.75 
4600                    Chips and Guacamole     $4.45 
4601                      Canned Soft Drink     $1.25 
4602                       Barbacoa Burrito     $9.25 
4603                       Barbacoa Burrito     $9.25 
4604                           Chicken Bowl     $8.75 
4605                    Chips and Guacamole     $4.45 
4606                      Canned Soft Drink     $1.25 
4607                          Steak Burrito    $11.75 
4608                         Veggie Burrito    $11.25 
4609                      Canned Soft Drink     $1.25 
4610                          Steak Burrito    $11.75 
4611                         Veggie Burrito    $11.25 
4612                          Carnitas Bowl     $9.25 
4613                                  Chips     $2.15 
4614                          Bottled Water     $1.50 
4615                     Chicken Soft Tacos     $8.75 
4616                    Chips and Guacamole     $4.45 
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [152]:
df.sort_values(by="item_name")

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [173]:
t = pd.to_numeric(df.item_price.str[1:])
z = t.sort_values(ascending=False)
z

3598    44.25
3480    35.25
1254    35.00
3602    35.00
3601    33.75
409     32.94
1255    27.75
3603    27.75
3636    26.25
3634    26.25
1514    26.25
3334    26.07
613     23.78
281     23.78
1566    23.50
4307    23.50
1753    23.50
3754    23.50
506     23.50
4427    23.50
2954    22.96
633     22.50
3507    22.50
4423    22.50
816     22.50
213     22.50
2419    22.50
1429    22.50
1923    22.50
2510    22.50
        ...  
1953     1.09
3434     1.09
2520     1.09
414      1.09
251      1.09
1396     1.09
248      1.09
247      1.09
246      1.09
87       1.09
434      1.09
438      1.09
180      1.09
2922     1.09
1948     1.09
2981     1.09
2538     1.09
3361     1.09
3897     1.09
1945     1.09
2544     1.09
2545     1.09
1457     1.09
2961     1.09
473      1.09
2562     1.09
107      1.09
3926     1.09
821      1.09
1140     1.09
Name: item_price, Length: 4622, dtype: float64

In [191]:

df.sort_values(by="item_price", ascending=False)[0:1]

order_id  quantity                     item_name choice_description  \
3598      1443        15  Chips and Fresh Tomato Salsa                NaN   

      item_price  
3598       44.25

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.6+ KB


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [195]:
df.item_name.value_counts()["Veggie Salad Bowl"]

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [198]:
df["item_name"].value_counts()["Canned Soda"]

104

In [70]:
# Импортировать NumPy под именем np

# import numpy as np
# Напечатать версию и конфигурацию

# print(np.__version__)
# np.show_config()
# Создать вектор (одномерный массив) размера 10, заполненный нулями

# Z = np.zeros(10)
# print(Z)
# Создать вектор размера 10, заполненный единицами

# Z = np.ones(10)
# print(Z)
# Создать вектор размера 10, заполненный числом 2.5

# Z = np.full(10, 2.5)
# print(Z)
# Как получить документацию о функции numpy.add из командной строки?

# python3 -c "import numpy; numpy.info(numpy.add)"
# Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

# Z = np.zeros(10)
# Z[4] = 1
# print(Z)
# Создать вектор со значениями от 10 до 49

# Z = np.arange(10,50)
# print(Z)
# Развернуть вектор (первый становится последним)

# Z = np.arange(50)
# Z = Z[::-1]
# Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

# Z = np.arange(9).reshape(3,3)
# print(Z)
# Найти индексы ненулевых элементов в [1,2,0,0,4,0]

# nz = np.nonzero([1,2,0,0,4,0])
# print(nz)
# Создать 3x3 единичную матрицу

# Z = np.eye(3)
# print(Z)
# Создать массив 3x3x3 со случайными значениями

# Z = np.random.random((3,3,3))
# print(Z)
# Создать массив 10x10 со случайными значениями, найти минимум и максимум

# Z = np.random.random((10,10))
# Zmin, Zmax = Z.min(), Z.max()
# print(Zmin, Zmax)
# Создать случайный вектор размера 30 и найти среднее значение всех элементов

# Z = np.random.random(30)
# m = Z.mean()
# print(m)
# Создать матрицу с 0 внутри, и 1 на границах

# Z = np.ones((10,10))
# Z[1:-1,1:-1] = 0
# Выяснить результат следующих выражений

# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1
# Создать 5x5 матрицу с 1,2,3,4 под диагональю

# Z = np.diag(np.arange(1, 5), k=-1)
# print(Z)
# Создать 8x8 матрицу и заполнить её в шахматном порядке

# Z = np.zeros((8,8), dtype=int)
# Z[1::2,::2] = 1
# Z[::2,1::2] = 1
# print(Z)
# Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

# print(np.unravel_index(100, (6,7,8)))
# Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

# Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
# print(Z)
# Перемножить матрицы 5x3 и 3x2

# Z = np.dot(np.ones((5,3)), np.ones((3,2)))
# print(Z)
# Дан массив, поменять знак у элементов, значения которых между 3 и 8

# Z = np.arange(11)
# Z[(3 < Z) & (Z <= 8)] *= -1
# Создать 5x5 матрицу со значениями в строках от 0 до 4

# Z = np.zeros((5,5))
# Z += np.arange(5)
# print(Z)
# Есть генератор, сделать с его помощью массив

# def generate():
#     for x in xrange(10):
#         yield x
# Z = np.fromiter(generate(),dtype=float,count=-1)
# print(Z)
# Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

# Z = np.linspace(0,1,12)[1:-1]
# print(Z)
# Отсортировать вектор

# Z = np.random.random(10)
# Z.sort()
# print(Z)
# Проверить, одинаковы ли 2 numpy массива

# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
# equal = np.allclose(A,B)
# print(equal)
# Сделать массив неизменяемым

# Z = np.zeros(10)
# Z.flags.writeable = False
# Z[0] = 1
# Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

# Z = np.random.random((10,2))
# X,Y = Z[:,0], Z[:,1]
# R = np.hypot(X, Y)
# T = np.arctan2(Y,X)
# print(R)
# print(T)
# Заменить максимальный элемент на ноль

# Z = np.random.random(10)
# Z[Z.argmax()] = 0
# print(Z)
# Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

# Z = np.zeros((10,10), [('x',float),('y',float)])
# Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
#                              np.linspace(0,1,10))
# print(Z)
# Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

# X = np.arange(8)
# Y = X + 0.5
# C = 1.0 / np.subtract.outer(X, Y)
# print(np.linalg.det(C))
# Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

# for dtype in [np.int8, np.int32, np.int64]:
#    print(np.iinfo(dtype).min)
#    print(np.iinfo(dtype).max)
# for dtype in [np.float32, np.float64]:
#    print(np.finfo(dtype).min)
#    print(np.finfo(dtype).max)
#    print(np.finfo(dtype).eps)
# Напечатать все значения в массиве

# np.set_printoptions(threshold=np.nan)
# Z = np.zeros((25,25))
# print(Z)
# Найти ближайшее к заданному значению число в заданном массиве

# Z = np.arange(100)
# v = np.random.uniform(0,100)
# index = (np.abs(Z-v)).argmin()
# print(Z[index])
# Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

#  Z = np.zeros(10, [ ('position', [ ('x', float, 1),
#                                    ('y', float, 1)]),
#                     ('color',    [ ('r', float, 1),
#                                    ('g', float, 1),
#                                    ('b', float, 1)])])
# print(Z)
# Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

# import scipy.spatial

# Z = np.random.random((10,2))
# D = scipy.spatial.distance.cdist(Z,Z)
# print(D)
# Преобразовать массив из float в int

# Z = np.arange(10, dtype=np.int32)
# Z = Z.astype(np.float32, copy=False)
# Дан файл:

# 1,2,3,4,5
# 6,,,7,8
# ,,9,10,11
# Как прочитать его?

# Z = np.genfromtxt("missing.dat", delimiter=",")
# Каков эквивалент функции enumerate для numpy массивов?

# Z = np.arange(9).reshape(3,3)
# for index, value in np.ndenumerate(Z):
#     print(index, value)
# for index in np.ndindex(Z.shape):
#     print(index, Z[index])
# Сформировать 2D массив с распределением Гаусса

# X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
# D = np.hypot(X, Y)
# sigma, mu = 1.0, 0.0
# G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
# print(G)
# Случайно расположить p элементов в 2D массив

# n = 10
# p = 3
# Z = np.zeros((n,n))
# np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
# Отнять среднее из каждой строки в матрице

# X = np.random.rand(5, 10)
# Y = X - X.mean(axis=1, keepdims=True)
# Отсортировать матрицу по n-ому столбцу

# Z = np.random.randint(0,10,(3,3))
# n = 1  # Нумерация с нуля
# print(Z)
# print(Z[Z[:,n].argsort()])
# Определить, есть ли в 2D массиве нулевые столбцы

# Z = np.random.randint(0,3,(3,10))
# print((~Z.any(axis=0)).any())
# Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

# Z = np.ones(10)
# I = np.random.randint(0,len(Z),20)
# Z += np.bincount(I, minlength=len(Z))
# print(Z)
# Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

# w,h = 16,16
# I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
# F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
# n = len(np.unique(F))
# print(np.unique(I))
# Дан четырехмерный массив, посчитать сумму по последним двум осям

# A = np.random.randint(0,10, (3,4,3,4))
# sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
# print(sum)
# Найти диагональные элементы произведения матриц

# # Slow version
# np.diag(np.dot(A, B))

# # Fast version
# np.sum(A * B.T, axis=1)

# # Faster version
# np.einsum("ij,ji->i", A, B).
# Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

# Z = np.array([1,2,3,4,5])
# nz = 3
# Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
# Z0[::nz+1] = Z
# print(Z0)
# Поменять 2 строки в матрице

# A = np.arange(25).reshape(5,5)
# A[[0,1]] = A[[1,0]]
# print(A)
# Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

# faces = np.random.randint(0,100,(10,3))
# F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
# F = F.reshape(len(F)*3,2)
# F = np.sort(F,axis=1)
# G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
# G = np.unique(G)
# print(G)
# Дан массив C; создать массив A, что np.bincount(A) == C

# C = np.bincount([1,1,2,3,4,4,6])
# A = np.repeat(np.arange(len(C)), C)
# print(A)
# Посчитать среднее, используя плавающее окно

# def moving_average(a, n=3):
#     ret = np.cumsum(a, dtype=float)
#     ret[n:] = ret[n:] - ret[:-n]
#     return ret[n - 1:] / n

# print(moving_average(np.arange(20), 3))
# Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

# from numpy.lib import stride_tricks

# def rolling(a, window):
#     shape = (a.size - window + 1, window)
#     strides = (a.itemsize, a.itemsize)
#     return stride_tricks.as_strided(a, shape=shape, strides=strides)
# Z = rolling(np.arange(10), 3)
# print(Z)
# Инвертировать булево значение, или поменять знак у числового массива без создания нового

# Z = np.random.randint(0,2,100)
# np.logical_not(arr, out=arr)

# Z = np.random.uniform(-1.0,1.0,100)
# np.negative(arr, out=arr)
# Рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку р, как вычислить расстояние от р до каждой линии i (P0[i],P1[i])

# def distance(P0, P1, p):
#     T = P1 - P0
#     L = (T**2).sum(axis=1)
#     U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
#     U = U.reshape(len(U),1)
#     D = P0 + U * T - p
#     return np.sqrt((D**2).sum(axis=1))

# P0 = np.random.uniform(-10,10,(10,2))
# P1 = np.random.uniform(-10,10,(10,2))
# p  = np.random.uniform(-10,10,( 1,2))
# print(distance(P0, P1, p))
# Дан массив. Написать функцию, выделяющую часть массива фиксированного размера с центром в данном элементе (дополненное значением fill если необходимо)

# Z = np.random.randint(0,10, (10,10))
# shape = (5,5)
# fill  = 0
# position = (1,1)

# R = np.ones(shape, dtype=Z.dtype)*fill
# P  = np.array(list(position)).astype(int)
# Rs = np.array(list(R.shape)).astype(int)
# Zs = np.array(list(Z.shape)).astype(int)

# R_start = np.zeros((len(shape),)).astype(int)
# R_stop  = np.array(list(shape)).astype(int)
# Z_start = (P - Rs//2)
# Z_stop  = (P + Rs//2)+Rs%2

# R_start = (R_start - np.minimum(Z_start, 0)).tolist()
# Z_start = (np.maximum(Z_start, 0)).tolist()
# R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
# Z_stop = (np.minimum(Z_stop,Zs)).tolist()

# r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
# z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
# R[r] = Z[z]
# print(Z)
# print(R)
# Посчитать ранг матрицы

# Z = np.random.uniform(0,1,(10,10))
# rank = np.linalg.matrix_rank(Z)
# Найти наиболее частое значение в массиве

# Z = np.random.randint(0,10,50)
# print(np.bincount(Z).argmax())
# Извлечь все смежные 3x3 блоки из 10x10 матрицы

# Z = np.random.randint(0,5,(10,10))
# n = 3
# i = 1 + (Z.shape[0] - n)
# j = 1 + (Z.shape[1] - n)
# C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
# print(C)
# Создать подкласс симметричных 2D массивов (Z[i,j] == Z[j,i])

# # Note: only works for 2d array and value setting using indices

# class Symetric(np.ndarray):
#     def __setitem__(self, (i,j), value):
#         super(Symetric, self).__setitem__((i,j), value)
#         super(Symetric, self).__setitem__((j,i), value)

# def symetric(Z):
#     return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

# S = symetric(np.random.randint(0,10,(5,5)))
# S[2,3] = 42
# print(S)
# Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

# p, n = 10, 20
# M = np.ones((p,n,n))
# V = np.ones((p,n,1))
# S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
# print(S)

# # It works, because:
# # M is (p,n,n)
# # V is (p,n,1)
# # Thus, summing over the paired axes 0 and 0 (of M and V independently),
# # and 2 and 1, to remain with a (n,1) vector.
# Дан массив 16x16, посчитать сумму по блокам 4x4

# Z = np.ones((16,16))
# k = 4
# S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
#                                        np.arange(0, Z.shape[1], k), axis=1)
# Написать игру "жизнь"

# def iterate(Z):
#     # Count neighbours
#     N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
#          Z[1:-1,0:-2]                + Z[1:-1,2:] +
#          Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

#     # Apply rules
#     birth = (N == 3) & (Z[1:-1,1:-1]==0)
#     survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
#     Z[...] = 0
#     Z[1:-1,1:-1][birth | survive] = 1
#     return Z

# Z = np.random.randint(0,2,(50,50))
# for i in range(100):
#     print(Z)
#     Z = iterate(Z)
# Найти n наибольших значений в массиве

# Z = np.arange(10000)
# np.random.shuffle(Z)
# n = 5

# print (Z[np.argpartition(-Z,n)[:n]])
# Построить прямое произведение массивов (все комбинации с каждым элементом)

# def cartesian(arrays):
#     arrays = [np.asarray(a) for a in arrays]
#     shape = map(len, arrays)

#     ix = np.indices(shape, dtype=int)
#     ix = ix.reshape(len(arrays), -1).T

#     for n, arr in enumerate(arrays):
#         ix[:, n] = arrays[n][ix[:, n]]

#     return ix

# print(cartesian(([1, 2, 3], [4, 5], [6, 7])))
# Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

# A = np.random.randint(0,5,(8,3))
# B = np.random.randint(0,5,(2,2))

# C = (A[..., np.newaxis, np.newaxis] == B)
# rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
# print(rows)
# Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

# Z = np.random.randint(0,5,(10,3))
# E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
# U = Z[~E]
# print(Z)
# print(U)
# Преобразовать вектор чисел в матрицу бинарных представлений

# I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
# print(np.unpackbits(I[:, np.newaxis], axis=1))
# Дан двумерный массив. Найти все различные строки

# Z = np.random.randint(0, 2, (6,3))
# T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
# _, idx = np.unique(T, return_index=True)
# uZ = Z[idx]
# print(uZ)
# Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

# # Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

# np.einsum('i->', A)       # np.sum(A)
# np.einsum('i,i->i', A, B) # A * B
# np.einsum('i,i', A, B)    # np.inner(A, B)
# np.einsum('i,j', A, B)    # np.outer(A, B)